        } catch (final StackOverflowError e) {
            throw new InputManipulationException("Possible Denial of Service attack by Stack Overflow");
